name: lagr_env
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - astropy
  - gdal
  - matplotlib
  - h5py
  - tqdm
  - xarray
  - rasterio
  - pandas
  - geopandas
  - fiona
  - pyproj
  - pyshp
  - shapely
  - netcdf4