name: lagr_env
channels:
  - conda-forge
dependencies:
  - setuptools
  - pip
  - numpy
  - scipy
  - gdal
  - rasterio
  - matplotlib
  - cartopy
  - h5py
  - netcdf4
  - xarray
  - pandas
  - geopandas
  - fiona
  - pyproj
  - pyshp
  - shapely
  - jupyter
  - pytmd
  - tqdm
  - flake8
  - pylint
  - pip:
    - matplotlib_scalebar